sudo: false
language: cpp
compiler:
    - gcc
    - clang

branches:
    only:
        - master

install:
    - if [ "$CXX" == "g++" ]; then export CXX=g++-4.8; fi

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - clang
            - ninja-build
            - libglew-dev

script:
    - python ./bootstrap.py --ci --cxx=$CC
    - ninja
